name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          logout: false
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Log in to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          logout: false
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # This is automatically provided

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            hihihi45/images:portfoliotest

      # Build and push Docker image to GitHub Container Registry
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/jack-bowden/portfoliotest:latest
